Lesson2
Michael-pixel-hub/django_new_project pull request #2
Opened 2022-02-10 17:12 UTC by Michael-pixel-hub

2022-02-11 14:10 UTC, Vokler requested changes

2022-02-11 14:10 UTC, Vokler commented on products/views.py
> +    with open('/home/michael/project_django/geekshop-server/geekshop/products/fixtures/products.json', 'r') as file:
А если вы запустите ваш проект на другом компьютере, в котором нет пути `/home/michael/project_django/...`

Надо что-то универсальное. Вспомните про BASE_DIR, про который мы говорили на 1ом уроке. И попробуйте с применением его исправить :)

2022-02-12 14:10 UTC, Michael-pixel-hub commented on products/views.py
> +    with open('/home/michael/project_django/geekshop-server/geekshop/products/fixtures/products.json', 'r') as file:
Готово!

2022-02-13 18:34 UTC, Vokler approved these changes

2022-02-13 18:34 UTC, merged